version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545:8545'
    command:
      # This env variable comes from the .env file in the directory in which the
      # docker-compose command is run. Here it will be ./packages/sidetree-ledger-ethereum
      - --mnemonic=${MNEMONIC}
      - --networkId='13370'
  ipfs:
    image: ipfs/go-ipfs:release
    ports:
      - '8080:8080'
      - '5001:5001'
      - '4001:4001'
  mongo:
    image: mongo
    restart: always
    ports:
     - '27017:27017'
    volumes:
     - './mongo-data:/data/db'
