version: "3"
services:
  # ganache:
  #   env_file:
  #     - .env
  #   container_name: ganache
  #   image: trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"
  #   entrypoint:
  #     - node
  #     - /app/ganache-core.docker.cli.js
  #     - --mnemonic
  #     - "$MNEMONIC"
  # ipfs:
  #   env_file:
  #     - .env
  #   container_name: ipfs
  #   image: ipfs/go-ipfs:release
  #   # volumes:
  #   #   - ./data/ipfs:/data/ipfs
  #   ports:
  #     - "8080:8080"
  #     - "5001:5001"
  #     - "4001:4001"
