version: '3'
services:
  ganache:
    env_file:
      - ./packages/sidetree-ledger-ethereum/.env
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545:8545'
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --mnemonic
      - '$MNEMONIC'
      - --networkId
      - '133700'
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:release
    ports:
      - '8080:8080'
      - '5001:5001'
      - '4001:4001'
  mongo:
    image: mongo
    restart: always
    ports:
     - '27017:27017'
    volumes:
     - './mongo-data:/data/db'
