name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      # pulls all commits (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
