name: CI

# Run on every push but not on tags
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  ci:
    if: "! contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Install
        run: npm run install:ci

      - name: Lint
        run: npm run lint 

      - name: Test
        run: npm run test 
