name: Sidetree js
on: [push]
jobs:
  sidetree-js:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/sidetree.js
      sidetree-common: ./packages/sidetree-common
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install sidetree-common
        working-directory: ${{ env.sidetree-common }}
        run: npm install
      - name: Install
        working-directory: ${{ env.working-directory }}
        run: npm install
      - name: Lint
        working-directory: ${{ env.working-directory }}
        run: npm run lint
      - name: Test
        working-directory: ${{ env.working-directory }}
        run: npm run test
      - name: Build
        working-directory: ${{ env.working-directory }}
        run: npm run build
