name: Sidetree CAS IPFS
on: [push]
jobs:
  sidetree-cas-ipfs:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Start Docker
        run: docker-compose up -d
      - name: Configure IPFS Access-Control-Allow-Origin
        run: |
          docker exec ipfs ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
      - name: Configure IPFS Access-Control-Allow-Methods
        run: |
          docker exec ipfs ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
      - name: Restart Docker
        run: docker-compose restart
      - name: Check Docker Logs
        run: docker-compose logs
      - name: Get IPFS Node ID
        run: curl -s -X GET http://127.0.0.1:5001/api/v0/id | jq '.'
