name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Setup Stack
        run: docker-compose up -d
      - name: Wait for IPFS
        run: sleep 5
      - name: Get IPFS Node ID
        run: curl -s -X GET http://127.0.0.1:5001/api/v0/id | jq '.'
