name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Setup Stack
        run: docker-compose up -d
      - name: Get IPFS Node ID
        run: docker run --network container:ipfs appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:5001/api/v0/id | jq '.'
        # run: curl -X GET http://127.0.0.1:5001/api/v0/id
